[2023-11-29T07:20:01.378+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airflow_stores_pg_etl.get_data manual__2023-11-29T07:19:51.940410+00:00 [queued]>
[2023-11-29T07:20:01.383+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airflow_stores_pg_etl.get_data manual__2023-11-29T07:19:51.940410+00:00 [queued]>
[2023-11-29T07:20:01.383+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T07:20:01.383+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-29T07:20:01.383+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T07:20:01.434+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): get_data> on 2023-11-29 07:19:51.940410+00:00
[2023-11-29T07:20:01.439+0000] {standard_task_runner.py:55} INFO - Started process 26729 to run task
[2023-11-29T07:20:01.442+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_stores_pg_etl', 'get_data', 'manual__2023-11-29T07:19:51.940410+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpr2i9ofjd']
[2023-11-29T07:20:01.443+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_data
[2023-11-29T07:20:01.502+0000] {task_command.py:388} INFO - Running <TaskInstance: airflow_stores_pg_etl.get_data manual__2023-11-29T07:19:51.940410+00:00 [running]> on host codespaces-0b6ae8
[2023-11-29T07:20:01.681+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=airflow_stores_pg_etl
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T07:19:51.940410+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-29T07:19:51.940410+00:00
[2023-11-29T07:20:01.683+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-29T07:20:01.683+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'kaggle datasets download kzmontage/sales-from-different-stores -p /workspaces/hands-on-introduction-data-engineering-4395021/dataset_temp']
[2023-11-29T07:20:01.697+0000] {subprocess.py:86} INFO - Output:
[2023-11-29T07:20:03.167+0000] {subprocess.py:93} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/codespace/.kaggle/kaggle.json'
[2023-11-29T07:20:03.168+0000] {subprocess.py:93} INFO - sales-from-different-stores.zip: Skipping, found more recently modified local copy (use --force to force download)
[2023-11-29T07:20:03.224+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-29T07:20:03.396+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=airflow_stores_pg_etl, task_id=get_data, execution_date=20231129T071951, start_date=20231129T072001, end_date=20231129T072003
[2023-11-29T07:20:03.469+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-29T07:20:03.488+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
